// Google Identity Services (client-only)
function decodeJwtPayload(jwt){try{const b=jwt.split('.')[1];const s=b.replace(/-/g,'+').replace(/_/g,'/');const j=decodeURIComponent(atob(s).split('').map(c=>'%' + ('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));return JSON.parse(j);}catch(e){console.error('JWT decode error',e);return null;}}
function handleGoogleCredential(resp){const p=decodeJwtPayload(resp.credential);if(!p)return;const user={sub:p.sub,name:p.name,email:p.email,picture:p.picture};try{localStorage.setItem('rce_user',JSON.stringify(user));}catch{} applyLoggedInUI(user);}
function applyLoggedInUI(user){const userInfo=document.getElementById('userInfo');const signInBtn=document.getElementById('googleSignInBtn');const avatar=document.getElementById('userAvatar');const nameEl=document.getElementById('userName');if(user){if(avatar) avatar.src=user.picture||''; if(nameEl) nameEl.textContent=user.name||''; if(userInfo) userInfo.style.display='flex'; if(signInBtn) signInBtn.style.display='none'; document.body.classList.add('logged-in');}else{if(userInfo) userInfo.style.display='none'; if(signInBtn) signInBtn.style.display=''; document.body.classList.remove('logged-in');}}
function initGoogleAuth(){const meta=document.querySelector('meta[name="google-signin-client_id"]');const clientId=meta&&meta.getAttribute('content');if(!clientId){console.warn('Missing Google client ID');return;} if(!(window.google&&google.accounts&&google.accounts.id)){setTimeout(initGoogleAuth,300);return;} google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:false,context:'signin'}); const btn=document.getElementById('googleSignInBtn'); if(btn){google.accounts.id.renderButton(btn,{theme:'outline',size:'large',shape:'pill',text:'signin_with',logo_alignment:'left'});} }
function signOut(){try{localStorage.removeItem('rce_user');}catch{} if(window.google&&google.accounts&&google.accounts.id){google.accounts.id.disableAutoSelect();} applyLoggedInUI(null);} 
document.addEventListener('DOMContentLoaded',()=>{try{const saved=localStorage.getItem('rce_user'); if(saved) applyLoggedInUI(JSON.parse(saved)); else applyLoggedInUI(null);}catch{applyLoggedInUI(null);} const signOutBtn=document.getElementById('signOutBtn'); if(signOutBtn) signOutBtn.addEventListener('click',signOut); initGoogleAuth();});

// Minimal app interactivity demo to avoid blank page
(function(){const controls=document.getElementById('controls'); if(!controls) return; controls.innerHTML = '<button id="demoChord" class="btn">Play Demo Chord</button>'; const btn=document.getElementById('demoChord'); if(btn){ btn.addEventListener('click', ()=>{ if (typeof playChord==='function'){ playChord([261.63, 329.63, 392.00]); } }); }} )();
