// App logic: populate, render, and play chords
const NOTE_CLASSES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
function pcIndex(n){return NOTE_CLASSES.indexOf(n)}
function getRagasByTradition(trad){ if(trad==='Both') return RAGAS; return RAGAS.filter(r=>r.tradition===trad); }
function populateRagaSelect(){ const tradition=document.getElementById('tradition').value; const sel=document.getElementById('ragaSelect'); sel.innerHTML=''; getRagasByTradition(tradition).forEach(r=>{ const opt=document.createElement('option'); opt.value=r.id; opt.textContent=r.name+' ('+r.tradition+')'; sel.appendChild(opt); }); }
function showRagaInfo(r){ const meta=document.getElementById('ragaMeta'); const pkd=document.getElementById('pakad'); meta.innerHTML=`<div class="badge">Tradition: ${r.tradition}</div><div class="badge">Vadi: ${r.vadi||'-'}</div><div class="badge">Samvadi: ${r.samvadi||'-'}</div><div class="badge">Pitch classes (C as Sa): ${r.pitchClassesC.join(', ')}</div>`; pkd.innerHTML=`<div class="badge">Pakad/Prayog: ${(Array.isArray(r.pakad)?r.pakad.join(' • '): (r.pakad||'-'))}</div>`; }
function simpleChordCandidates(pcs){ const tri=[]; for(let i=0;i<pcs.length;i++){ const root=pcs[i]; const idx=pcIndex(root); const m3=NOTE_CLASSES[(idx+3)%12]; const M3=NOTE_CLASSES[(idx+4)%12]; const p5=NOTE_CLASSES[(idx+7)%12]; if(pcs.includes(M3)&&pcs.includes(p5)) tri.push({name:`${root} maj`,tones:[root,M3,p5]}); if(pcs.includes(m3)&&pcs.includes(p5)) tri.push({name:`${root} min`,tones:[root,m3,p5]}); } return tri.slice(0,18); }
function renderChords(chords){ const grid=document.getElementById('chordsGrid'); grid.innerHTML=''; chords.forEach(ch=>{ const card=document.createElement('div'); card.className='chord-card'; card.innerHTML=`<strong>${ch.name}</strong><div class="badge">${ch.tones.join(' - ')}</div>`; card.addEventListener('click',()=>{ const c4=261.63; const freqs=ch.tones.map(t=>{ const semis=pcIndex(t)-pcIndex('C'); return c4*Math.pow(2, semis/12); }); if(typeof playChordFreqs==='function') playChordFreqs(freqs); }); grid.appendChild(card); }); }
function renderPhrases(r){ const el=document.getElementById('phrasesList'); const items=Array.isArray(r.pakad)?r.pakad:[r.pakad||'-']; el.innerHTML=items.map(p=>`<div class="badge">${p}</div>`).join(''); }
function initApp(){ populateRagaSelect(); const sel=document.getElementById('ragaSelect'); const r=(RAGAS.find(x=>x.id===sel.value)) || getRagasByTradition('Both')[0]; if(r){ showRagaInfo(r); renderChords(simpleChordCandidates(r.pitchClassesC)); renderPhrases(r); }
  document.getElementById('tradition').addEventListener('change',()=>{ populateRagaSelect(); const rr=RAGAS.find(x=>x.id===document.getElementById('ragaSelect').value); if(rr){ showRagaInfo(rr); renderChords(simpleChordCandidates(rr.pitchClassesC)); renderPhrases(rr); } });
  document.getElementById('ragaSelect').addEventListener('change',e=>{ const rr=RAGAS.find(x=>x.id===e.target.value); if(rr){ showRagaInfo(rr); renderChords(simpleChordCandidates(rr.pitchClassesC)); renderPhrases(rr); } });
  document.getElementById('generateBtn').addEventListener('click',()=>{ const rr=RAGAS.find(x=>x.id===document.getElementById('ragaSelect').value); if(rr) renderChords(simpleChordCandidates(rr.pitchClassesC));});
  document.getElementById('playDroneBtn').addEventListener('click',()=>{ const on=toggleDrone('C'); document.getElementById('playDroneBtn').textContent=on?'Stop Drone':'Play/Stop Drone'; }); }

document.addEventListener('DOMContentLoaded', initApp);

/* === Google Identity Services (non-breaking) === */
function decodeJwtPayload(jwt){try{const b=jwt.split('.')[1];const s=b.replace(/-/g,'+').replace(/_/g,'/');const j=decodeURIComponent(atob(s).split('').map(c=>'%' + ('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));return JSON.parse(j);}catch(e){console.error('JWT decode error',e);return null;}}
function handleGoogleCredential(resp){const p=decodeJwtPayload(resp.credential); if(!p) return; const user={sub:p.sub,name:p.name,email:p.email,picture:p.picture}; try{localStorage.setItem('rce_user',JSON.stringify(user));}catch{} applyLoggedInUI(user);} 
function applyLoggedInUI(user){ const userInfo=document.getElementById('userInfo'); const signInBtn=document.getElementById('googleSignInBtn'); const avatar=document.getElementById('userAvatar'); const nameEl=document.getElementById('userName'); if(user){ if(avatar) avatar.src=user.picture||''; if(nameEl) nameEl.textContent=user.name||''; if(userInfo) userInfo.style.display='flex'; if(signInBtn) signInBtn.style.display='none'; document.body.classList.add('logged-in'); } else { if(userInfo) userInfo.style.display='none'; if(signInBtn) signInBtn.style.display=''; document.body.classList.remove('logged-in'); } }
function initGoogleAuth(){ const meta=document.querySelector('meta[name="google-signin-client_id"]'); const clientId=meta&&meta.getAttribute('content'); if(!clientId || !(window.google&&google.accounts&&google.accounts.id)){ setTimeout(initGoogleAuth,300); return; } google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:false,context:'signin',ux_mode:'popup'}); const btn=document.getElementById('googleSignInBtn'); if(btn){ google.accounts.id.renderButton(btn,{theme:'outline',size:'large',shape:'pill',text:'signin_with',logo_alignment:'left'}); } }
function signOut(){ try{localStorage.removeItem('rce_user');}catch{} if(window.google&&google.accounts&&google.accounts.id){ google.accounts.id.disableAutoSelect(); } applyLoggedInUI(null); }

document.addEventListener('DOMContentLoaded',()=>{ try{ const saved=localStorage.getItem('rce_user'); if(saved) applyLoggedInUI(JSON.parse(saved)); else applyLoggedInUI(null); }catch{ applyLoggedInUI(null); } const b=document.getElementById('signOutBtn'); if(b) b.addEventListener('click', signOut); initGoogleAuth(); });
/* === End GIS === */
